### ISSUE TITLE
[ApplicationAutoScaling] graph db loader

### ISSUE THREAD

**Issue by joshlarsen** [OpenCSPM/opencspm#153]
Missing loader for `ApplicationAutoScaling`.
---
Dear OpenCSPM,

I am rather new to this Docker stuff, and my question may be just my lack of knowledge around the platform. In short, when I create the custom JSON file, extract to the folder specified for OpenCSPM to import. I then attempt to reload the data _(via web console / docker-compose down/up)_ I get the following error.

worker_1  | Warning: no Backup loader defined for asset type: protected_resource
worker_1  | Loader job failed - NameError uninitialized constant AWSLoader::ApplicationAutoScaling (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:25:in `const_get')
worker_1  | Runner job failed - NameError uninitialized constant AWSLoader::ApplicationAutoScaling (/app/app/jobs/lib/loader/asset/loaders/aws_loader/_resource_loader.rb:25:in `const_get')
worker_1  | I, [2021-04-21T14:06:28.283442 #1]  INFO -- : [ActiveJob] [RunnerJob] [f82dc9b3-19f5-485b-b664-f60a937113ed] Performed RunnerJob (Job ID: f82dc9b3-19f5-485b-b664-f60a937113ed) from Sidekiq(default) in 44876.54ms
worker_1  | 2021-04-21T14:06:28.295Z pid=1 tid=gp5k0oly1 class=RunnerJob jid=535e242bd81a6098d34bbb62 elapsed=44.947 INFO: done

I hope this is just my lack of knowledge around the dependencies of the tool and you all can provide some insight as to remedy. 

On another note, tool is AWESOME and one of the easiest to get up and working from other tools I've used. Thank you all for creating this and hopefully my issue is easily resolve with a few commands on my part.

Thanks in advance!

William

_Originally posted by @Nebula-Ninjas in https://github.com/OpenCSPM/opencspm/discussions/152_

**Comment by joshlarsen** [comment]
Fixed by https://github.com/OpenCSPM/opencspm/commit/75ef9567ed16bbd68f040f1b1904b07f5170834f
