### ISSUE TITLE
Loader Job Failed - NoMethodError | asset_router.rb

### ISSUE THREAD

**Issue by Nebula-Ninjas** [OpenCSPM/opencspm#175]
**Describe the bug**
I am importing a custom JSON file and the Docker worker_1 container is unable to load the custom JSON file. Getting the following error:

Loader job failed - NoMethodError undefined method `keys' for #<Array:0x000055c06fb0e1d8> (/app/app/jobs/lib/loader/asset/asset_router.rb:29:in `route')

**To Reproduce**
1. Run aws_recon docker image and output the JSON file.
2. Go thru the process of using a custom JSON file.
3. Run OpenCSPM containers
4. Get the following error:

worker_1  | Loader job failed - NoMethodError undefined method `keys' for #<Array:0x000055c06fb0e1d8> (/app/app/jobs/lib/loader/asset/asset_router.rb:29:in `route')
worker_1  | Runner job failed - NoMethodError undefined method `keys' for #<Array:0x000055c06fb0e1d8> (/app/app/jobs/lib/loader/asset/asset_router.rb:29:in `route')

**Expected behavior**
For it to either fail on an unsupported / missing AWS service or load the custom JSON file.

**Docker information (please complete the following information):**

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

**Cloud provider (if applicable):**
AWS

Also ran the docker command to remove orphans, deleted all containers/images and re-pulled to make sure it wasn't something local causing the issue.

Thanks in advance,

William

**Comment by mihaiturcu** [comment]
Running into the same issue.
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

exporting json via 

docker run -t --rm \
  -e AWS_REGION="us-west-1" \
  -e AWS_ACCESS_KEY_ID="xxxxxx" \
  -e AWS_SECRET_ACCESS_KEY="xxxx" \
  -v $(pwd)/output.json:/recon/output.json \
  darkbitio/aws_recon:latest aws_recon -v -s S3 -f custom > output.json

Thanks

**Comment by joshlarsen** [comment]
The cause of this error is usually that your input JSON file is not NDJSON. If the first character of that file is `[`, it’s probably regular JSON and won’t import.

OpenCSPM requires NDJSON so that very large environments can be imported (line by line) without running out of memory.

**Comment by Nebula-Ninjas** [comment]
@joshlarsen I missed adding the correct flag for that, I left off the `-j` and re-ran the tool and it doesn't throw the error anymore. However, I do get a `Loader job failed` error and I'll fix it on my repo and submit it to you guys. Thanks for the quick response and turnaround!

@mihaiturcu correct command should be the following, add in additional flags you need:

`docker run -t --rm \
-e AWS_REGION=DEFAULT_REGION \
-e AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY \
-e AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY \
-v $(pwd)/output.json:/recon/output.json \
darkbitio/aws_recon:latest \
aws_recon -j -r global,us-east-1 -f custom > output.json`

This is what has been working for me.

William
